### ISSUE TITLE
Папка aux под Windows

### ISSUE THREAD

**Issue by arwer13** [MMCS-SFEDU/mmcs_sfedu_thesis#2]
На работе нужно было склонировать под Windows, который создать папку "aux" не позволяет. Для себя переименовал в auxiliary.

**Comment by ulysses4ever** [comment]
Жесть какая. Спасибо, надо переделать. Я склоняюсь к aux_ или чего-то такое, потому что имя этого каталога, с моей точки зрения, должно быть коротким.
