### ISSUE TITLE
Номер следующего после титульного листа

### ISSUE THREAD

**Issue by arwer13** [MMCS-SFEDU/mmcs_sfedu_thesis#4]
Как притяно нумеровать следующий после титульного лист? 1 или 2?

**Comment by ulysses4ever** [comment]
2

**Comment by arwer13** [comment]
Быстро :)
Спасибо.

**Comment by ulysses4ever** [comment]
Так лето же.

Искать в гостах лень, но в [требованиях для итэшников](http://it.mmcs.sfedu.ru/docs/IT-papers-2015.pdf), котоыре имеют статус официальных, явно об этом написано:

> Нумерация страниц начинается с титульного листа, но
> на самом титульном листе номер не указывается.

**Comment by arwer13** [comment]
А кто такие требования пишет? И есть ли оное для прикладников?

**Comment by arwer13** [comment]
Этого года.

**Comment by ulysses4ever** [comment]
Для ИТ они составляются в недрах института руководителя направления.

На ПМИ, как всегда, разброд и шатания. Ничего подобного нет.

Смысл в том, что это оформительский стандарт, он не может по разному
решаться, если здравомыслящие люди его пишут.

14 июня 2015 г., 22:08 пользователь Veremeenko Artyom <
notifications@github.com> написал:
