### ISSUE TITLE
Разделы, постановка задачи и разбиения страниц

### ISSUE THREAD

**Issue by siamezzze** [MMCS-SFEDU/mmcs_sfedu_thesis#5]
Тут накопилось мелких (и не очень) вопросов по оформлению, можете подсказать?
1) Должны ли разделы начинаться на новой станице?
2) Должна ли быть постановка задачи на отдельной странице?
3) Где вообще должна быть постановка задачи? Из рекомендаций выходит, что перед оглавлением - а в само оглавление она попасть должна или нет?
4) Приложения идут после списка литературы? Включаются в оглавление?
Спасибо.

**Comment by ulysses4ever** [comment]
1) по желанию. В шаблоне реализованы оба варианта (см. Комментарии в preamble.tex): с новой называется Главы, а не с новой — разделы (это условно так разделено, для удобства). Я советую тексты длиннее 35 страниц разбивать на главы (то есть делать с новой страницы).

2-3) постановка должна быть отдельно и никуда не включается. Логика такая: текст дипломной работы принадлежит вам, а постановка принадлежит руководителю. Потому это разные документы. Но для удобства их хранят в одной папочке. 

4) после. Включаются.

**Comment by siamezzze** [comment]
Спасибо!
