### ISSUE TITLE
Примеры

### ISSUE THREAD

**Issue by artemkonenko** [MMCS-SFEDU/mmcs_sfedu_thesis#7]
Если использовать окружение [myexamples](https://github.com/MMCS-SFEDU/mmcs_sfedu_thesis/blob/master/core/theorem_styles.tex#L40) для приведения нескольких примеров подряд, то можно заметить, что первый из примеров не имеет отступа при рендеринге, а остальные имеют. @ulysses4ever подскажите, как можно его исправить, чтобы всё было одинаково?

**Comment by ulysses4ever** [comment]
Было бы хорошо MWE (minimal working example) желательно ссылкой на Оверлиф.

**Comment by artemkonenko** [comment]
Ой, это я забыл разделитель добавить, потому что невнимательно прочел его определение.
Но вопрос теперь такой: как изменить это окружение так, чтобы примеры имели отступы?
[Вот обрезал до MWE.](https://www.overleaf.com/2908570dgxcmt)

**Comment by ulysses4ever** [comment]
Вас интересует абзацный отступ? Нужно просто ставить нормальные абзацы (пустые строки), а не разрывы строк (\\). Разрывы строк вообще достаточно редко используются, если нормально верстать.

Первый абзац пока без отступа. Это разумно, потому что заголовк тоже без отсутпа (первый абзац всегда должен иметь такой же отступ, как заголовок, если последний выравнен по левому краю). Быстро сказать, как его сделать с отступом, не могу: нужно подумать, это если вы точно хотите его с отступом.

Ещё можно делать список (enumerate) внутри.

**Comment by artemkonenko** [comment]
Ну вот у меня и были пустые строки вместо обратных слэшей, а потом я увидел в определении `\theoremseparator {\\}`.
За подсказку с нумерацией спасибо, это даже лучше чем просто отступы.
